from pyddl import *

def get_precedence():
    precedence = {  # Can handle 4x4 grid as of now #2,1
        ('place_component', 'triangle', 1, 2): (neg(('blank', 1, 1)),),
        ('place_component', 'triangle', 2, 2): (neg(('blank', 2, 1)),),
        ('place_component', 'triangle', 3, 2): (neg(('blank', 3, 1)),),
        ('place_component', 'triangle', 4, 2): (neg(('blank', 4, 1)),),

        ('place_component', 'circle', 1, 2): (neg(('blank', 1, 1)),),
        ('place_component', 'circle', 2, 2): (neg(('blank', 2, 1)),),
        ('place_component', 'circle', 3, 2): (neg(('blank', 3, 1)),),
        ('place_component', 'circle', 4, 2): (neg(('blank', 4, 1)),),

        ('place_component', 'square', 1, 2): (neg(('blank', 1, 1)),),
        ('place_component', 'square', 2, 2): (neg(('blank', 2, 1)),),
        ('place_component', 'square', 3, 2): (neg(('blank', 3, 1)),),
        ('place_component', 'square', 4, 2): (neg(('blank', 4, 1)),),

        ##### 3,2
        ('place_component', 'triangle', 1, 3): (neg(('blank', 1, 2)),),
        ('place_component', 'triangle', 2, 3): (neg(('blank', 2, 2)),),
        ('place_component', 'triangle', 3, 3): (neg(('blank', 3, 2)),),
        ('place_component', 'triangle', 4, 3): (neg(('blank', 4, 2)),),

        ('place_component', 'circle', 1, 3): (neg(('blank', 1, 2)),),
        ('place_component', 'circle', 2, 3): (neg(('blank', 2, 2)),),
        ('place_component', 'circle', 3, 3): (neg(('blank', 3, 2)),),
        ('place_component', 'circle', 4, 3): (neg(('blank', 4, 2)),),

        ('place_component', 'square', 1, 3): (neg(('blank', 1, 2)),),
        ('place_component', 'square', 2, 3): (neg(('blank', 2, 2)),),
        ('place_component', 'square', 3, 3): (neg(('blank', 3, 2)),),
        ('place_component', 'square', 4, 3): (neg(('blank', 4, 2)),),

        ##### 4,3
        ('place_component', 'triangle', 1, 4): (neg(('blank', 1, 3)),),
        ('place_component', 'triangle', 2, 4): (neg(('blank', 2, 3)),),
        ('place_component', 'triangle', 3, 4): (neg(('blank', 3, 3)),),
        ('place_component', 'triangle', 4, 4): (neg(('blank', 4, 3)),),

        ('place_component', 'circle', 1, 4): (neg(('blank', 1, 3)),),
        ('place_component', 'circle', 2, 4): (neg(('blank', 2, 3)),),
        ('place_component', 'circle', 3, 4): (neg(('blank', 3, 3)),),
        ('place_component', 'circle', 4, 4): (neg(('blank', 4, 3)),),

        ('place_component', 'square', 1, 4): (neg(('blank', 1, 3)),),
        ('place_component', 'square', 2, 4): (neg(('blank', 2, 3)),),
        ('place_component', 'square', 3, 4): (neg(('blank', 3, 3)),),
        ('place_component', 'square', 4, 4): (neg(('blank', 4, 3)),),

        ### 2,1
        ('place_component', 'triangle_2', 1, 2): (neg(('blank', 1, 1)),),
        ('place_component', 'triangle_2', 2, 2): (neg(('blank', 2, 1)),),
        ('place_component', 'triangle_2', 3, 2): (neg(('blank', 3, 1)),),
        ('place_component', 'triangle_2', 4, 2): (neg(('blank', 4, 1)),),

        ('place_component', 'circle_2', 1, 2): (neg(('blank', 1, 1)),),
        ('place_component', 'circle_2', 2, 2): (neg(('blank', 2, 1)),),
        ('place_component', 'circle_2', 3, 2): (neg(('blank', 3, 1)),),
        ('place_component', 'circle_2', 4, 2): (neg(('blank', 4, 1)),),

        ('place_component', 'square_2', 1, 2): (neg(('blank', 1, 1)),),
        ('place_component', 'square_2', 2, 2): (neg(('blank', 2, 1)),),
        ('place_component', 'square_2', 3, 2): (neg(('blank', 3, 1)),),
        ('place_component', 'square_2', 4, 2): (neg(('blank', 4, 1)),),

        ## 2,3
        ('place_component', 'triangle_2', 1, 3): (neg(('blank', 1, 2)),),
        ('place_component', 'triangle_2', 2, 3): (neg(('blank', 2, 2)),),
        ('place_component', 'triangle_2', 3, 3): (neg(('blank', 3, 2)),),
        ('place_component', 'triangle_2', 4, 3): (neg(('blank', 4, 2)),),

        ('place_component', 'circle_2', 1, 3): (neg(('blank', 1, 2)),),
        ('place_component', 'circle_2', 2, 3): (neg(('blank', 2, 2)),),
        ('place_component', 'circle_2', 3, 3): (neg(('blank', 3, 2)),),
        ('place_component', 'circle_2', 4, 3): (neg(('blank', 4, 2)),),

        ('place_component', 'square_2', 1, 3): (neg(('blank', 1, 2)),),
        ('place_component', 'square_2', 2, 3): (neg(('blank', 2, 2)),),
        ('place_component', 'square_2', 3, 3): (neg(('blank', 3, 2)),),
        ('place_component', 'square_2', 4, 3): (neg(('blank', 4, 2)),),

        ## 4,3
        ('place_component', 'triangle_2', 1, 4): (neg(('blank', 1, 3)),),
        ('place_component', 'triangle_2', 2, 4): (neg(('blank', 2, 3)),),
        ('place_component', 'triangle_2', 3, 4): (neg(('blank', 3, 3)),),
        ('place_component', 'triangle_2', 4, 4): (neg(('blank', 4, 3)),),

        ('place_component', 'circle_2', 1, 4): (neg(('blank', 1, 3)),),
        ('place_component', 'circle_2', 2, 4): (neg(('blank', 2, 3)),),
        ('place_component', 'circle_2', 3, 4): (neg(('blank', 3, 3)),),
        ('place_component', 'circle_2', 4, 4): (neg(('blank', 4, 3)),),

        ('place_component', 'square_2', 1, 4): (neg(('blank', 1, 3)),),
        ('place_component', 'square_2', 2, 4): (neg(('blank', 2, 3)),),
        ('place_component', 'square_2', 3, 4): (neg(('blank', 3, 3)),),
        ('place_component', 'square_2', 4, 4): (neg(('blank', 4, 3)),),



        ('grid_to_grid', 1, 1, 1, 2): (('blank', 10, 0),), # some unachievable condition, because these actions are not allowed
        ('grid_to_grid', 1, 1, 1, 3): (('blank', 10, 0),),
        ('grid_to_grid', 1, 1, 1, 4): (('blank', 10, 0),),
        ('grid_to_grid', 2, 1, 2, 2): (('blank', 10, 0),),
        ('grid_to_grid', 2, 1, 2, 3): (('blank', 10, 0),),
        ('grid_to_grid', 2, 1, 2, 4): (('blank', 10, 0),),
        ('grid_to_grid', 3, 1, 3, 2): (('blank', 10, 0),),
        ('grid_to_grid', 3, 1, 3, 3): (('blank', 10, 0),),
        ('grid_to_grid', 3, 1, 3, 4): (('blank', 10, 0),),
        ('grid_to_grid', 4, 1, 4, 2): (('blank', 10, 0),),
        ('grid_to_grid', 4, 1, 4, 3): (('blank', 10, 0),),
        ('grid_to_grid', 4, 1, 4, 4): (('blank', 10, 0),),

        ('grid_to_grid', 1, 2, 1, 1): (('blank', 10, 0),),
        ('grid_to_grid', 1, 2, 1, 2): (('blank', 10, 0),),
        ('grid_to_grid', 1, 2, 1, 3): (('blank', 10, 0),),
        ('grid_to_grid', 1, 2, 1, 4): (('blank', 10, 0),),
        ('grid_to_grid', 2, 2, 2, 1): (('blank', 10, 0),),
        ('grid_to_grid', 2, 2, 2, 2): (('blank', 10, 0),),
        ('grid_to_grid', 2, 2, 2, 3): (('blank', 10, 0),),
        ('grid_to_grid', 2, 2, 2, 4): (('blank', 10, 0),),
        ('grid_to_grid', 3, 2, 3, 1): (('blank', 10, 0),),
        ('grid_to_grid', 3, 2, 3, 2): (('blank', 10, 0),),
        ('grid_to_grid', 3, 2, 3, 3): (('blank', 10, 0),),
        ('grid_to_grid', 3, 2, 3, 4): (('blank', 10, 0),),
        ('grid_to_grid', 4, 2, 4, 1): (('blank', 10, 0),),
        ('grid_to_grid', 4, 2, 4, 2): (('blank', 10, 0),),
        ('grid_to_grid', 4, 2, 4, 3): (('blank', 10, 0),),
        ('grid_to_grid', 4, 2, 4, 4): (('blank', 10, 0),),

        ('grid_to_grid', 1, 3, 1, 1): (('blank', 10, 0),),
        ('grid_to_grid', 1, 3, 1, 2): (('blank', 10, 0),),
        ('grid_to_grid', 1, 3, 1, 3): (('blank', 10, 0),),
        ('grid_to_grid', 1, 3, 1, 4): (('blank', 10, 0),),
        ('grid_to_grid', 2, 3, 2, 1): (('blank', 10, 0),),
        ('grid_to_grid', 2, 3, 2, 2): (('blank', 10, 0),),
        ('grid_to_grid', 2, 3, 2, 3): (('blank', 10, 0),),
        ('grid_to_grid', 2, 3, 2, 4): (('blank', 10, 0),),
        ('grid_to_grid', 3, 3, 3, 1): (('blank', 10, 0),),
        ('grid_to_grid', 3, 3, 3, 2): (('blank', 10, 0),),
        ('grid_to_grid', 3, 3, 3, 3): (('blank', 10, 0),),
        ('grid_to_grid', 3, 3, 3, 4): (('blank', 10, 0),),
        ('grid_to_grid', 4, 3, 4, 1): (('blank', 10, 0),),
        ('grid_to_grid', 4, 3, 4, 2): (('blank', 10, 0),),
        ('grid_to_grid', 4, 3, 4, 3): (('blank', 10, 0),),
        ('grid_to_grid', 4, 3, 4, 4): (('blank', 10, 0),),

        ('grid_to_grid', 1, 4, 1, 1): (('blank', 10, 0),),
        ('grid_to_grid', 1, 4, 1, 2): (('blank', 10, 0),),
        ('grid_to_grid', 1, 4, 1, 3): (('blank', 10, 0),),
        ('grid_to_grid', 1, 4, 1, 4): (('blank', 10, 0),),
        ('grid_to_grid', 2, 4, 2, 1): (('blank', 10, 0),),
        ('grid_to_grid', 2, 4, 2, 2): (('blank', 10, 0),),
        ('grid_to_grid', 2, 4, 2, 3): (('blank', 10, 0),),
        ('grid_to_grid', 2, 4, 2, 4): (('blank', 10, 0),),
        ('grid_to_grid', 3, 4, 3, 1): (('blank', 10, 0),),
        ('grid_to_grid', 3, 4, 3, 2): (('blank', 10, 0),),
        ('grid_to_grid', 3, 4, 3, 3): (('blank', 10, 0),),
        ('grid_to_grid', 3, 4, 3, 4): (('blank', 10, 0),),
        ('grid_to_grid', 4, 4, 4, 1): (('blank', 10, 0),),
        ('grid_to_grid', 4, 4, 4, 2): (('blank', 10, 0),),
        ('grid_to_grid', 4, 4, 4, 3): (('blank', 10, 0),),
        ('grid_to_grid', 4, 4, 4, 4): (('blank', 10, 0),),

        ################################################################################################################
        # now the actions that may be valid
        ('grid_to_grid', 1, 1, 2, 1): (('blank', 1, 2),),
        ('grid_to_grid', 1, 1, 2, 2): (neg(('blank', 2, 1)), ('blank', 1, 2),),
        ('grid_to_grid', 1, 1, 2, 3): (neg(('blank', 2, 2)), ('blank', 1, 2),),
        ('grid_to_grid', 1, 1, 2, 4): (neg(('blank', 2, 3)), ('blank', 1, 2),),
        ('grid_to_grid', 1, 1, 3, 1): (('blank', 1, 2),),
        ('grid_to_grid', 1, 1, 3, 2): (neg(('blank', 3, 1)), ('blank', 1, 2),),
        ('grid_to_grid', 1, 1, 3, 3): (neg(('blank', 3, 2)), ('blank', 1, 2),),
        ('grid_to_grid', 1, 1, 3, 4): (neg(('blank', 3, 3)), ('blank', 1, 2),),
        ('grid_to_grid', 1, 1, 4, 1): (('blank', 1, 2),),
        ('grid_to_grid', 1, 1, 4, 2): (neg(('blank', 4, 1)), ('blank', 1, 2),),
        ('grid_to_grid', 1, 1, 4, 3): (neg(('blank', 4, 2)), ('blank', 1, 2),),
        ('grid_to_grid', 1, 1, 4, 4): (neg(('blank', 4, 3)), ('blank', 1, 2),),

        ('grid_to_grid', 1, 2, 2, 1): (('blank', 1, 3),),
        ('grid_to_grid', 1, 2, 2, 2): (neg(('blank', 2, 1)), ('blank', 1, 3),),
        ('grid_to_grid', 1, 2, 2, 3): (neg(('blank', 2, 2)), ('blank', 1, 3),),
        ('grid_to_grid', 1, 2, 2, 4): (neg(('blank', 2, 3)), ('blank', 1, 3),),
        ('grid_to_grid', 1, 2, 3, 1): (('blank', 1, 3),),
        ('grid_to_grid', 1, 2, 3, 2): (neg(('blank', 3, 1)), ('blank', 1, 3),),
        ('grid_to_grid', 1, 2, 3, 3): (neg(('blank', 3, 2)), ('blank', 1, 3),),
        ('grid_to_grid', 1, 2, 3, 4): (neg(('blank', 3, 3)), ('blank', 1, 3),),
        ('grid_to_grid', 1, 2, 4, 1): (('blank', 1, 3),),
        ('grid_to_grid', 1, 2, 4, 2): (neg(('blank', 4, 1)), ('blank', 1, 3),),
        ('grid_to_grid', 1, 2, 4, 3): (neg(('blank', 4, 2)), ('blank', 1, 3),),
        ('grid_to_grid', 1, 2, 4, 4): (neg(('blank', 4, 3)), ('blank', 1, 3),),

        ('grid_to_grid', 1, 3, 2, 1): (('blank', 1, 4),),
        ('grid_to_grid', 1, 3, 2, 2): (neg(('blank', 2, 1)), ('blank', 1, 4),),
        ('grid_to_grid', 1, 3, 2, 3): (neg(('blank', 2, 2)), ('blank', 1, 4),),
        ('grid_to_grid', 1, 3, 2, 4): (neg(('blank', 2, 3)), ('blank', 1, 4),),
        ('grid_to_grid', 1, 3, 3, 1): (('blank', 1, 4),),
        ('grid_to_grid', 1, 3, 3, 2): (neg(('blank', 3, 1)), ('blank', 1, 4),),
        ('grid_to_grid', 1, 3, 3, 3): (neg(('blank', 3, 2)), ('blank', 1, 4),),
        ('grid_to_grid', 1, 3, 3, 4): (neg(('blank', 3, 3)), ('blank', 1, 4),),
        ('grid_to_grid', 1, 3, 4, 1): (('blank', 1, 4),),
        ('grid_to_grid', 1, 3, 4, 2): (neg(('blank', 4, 1)), ('blank', 1, 4),),
        ('grid_to_grid', 1, 3, 4, 3): (neg(('blank', 4, 2)), ('blank', 1, 4),),
        ('grid_to_grid', 1, 3, 4, 4): (neg(('blank', 4, 3)), ('blank', 1, 4),),

        ('grid_to_grid', 1, 4, 2, 2): (neg(('blank', 2, 1)),),
        ('grid_to_grid', 1, 4, 2, 3): (neg(('blank', 2, 2)),),
        ('grid_to_grid', 1, 4, 2, 4): (neg(('blank', 2, 3)),),
        ('grid_to_grid', 1, 4, 3, 2): (neg(('blank', 3, 1)),),
        ('grid_to_grid', 1, 4, 3, 3): (neg(('blank', 3, 2)),),
        ('grid_to_grid', 1, 4, 3, 4): (neg(('blank', 3, 3)),),
        ('grid_to_grid', 1, 4, 4, 2): (neg(('blank', 4, 1)),),
        ('grid_to_grid', 1, 4, 4, 3): (neg(('blank', 4, 2)),),
        ('grid_to_grid', 1, 4, 4, 4): (neg(('blank', 4, 3)),),

        ('grid_to_grid', 2, 1, 1, 1): (('blank', 2, 2),),
        ('grid_to_grid', 2, 1, 1, 2): (neg(('blank', 1, 1)), ('blank', 2, 2),),
        ('grid_to_grid', 2, 1, 1, 3): (neg(('blank', 1, 2)), ('blank', 2, 2),),
        ('grid_to_grid', 2, 1, 1, 4): (neg(('blank', 1, 3)), ('blank', 2, 2),),
        ('grid_to_grid', 2, 1, 3, 1): (('blank', 2, 2),),
        ('grid_to_grid', 2, 1, 3, 2): (neg(('blank', 3, 1)), ('blank', 2, 2),),
        ('grid_to_grid', 2, 1, 3, 3): (neg(('blank', 3, 2)), ('blank', 2, 2),),
        ('grid_to_grid', 2, 1, 3, 4): (neg(('blank', 3, 3)), ('blank', 2, 2),),
        ('grid_to_grid', 2, 1, 4, 1): (('blank', 2, 2),),
        ('grid_to_grid', 2, 1, 4, 2): (neg(('blank', 4, 1)), ('blank', 2, 2),),
        ('grid_to_grid', 2, 1, 4, 3): (neg(('blank', 4, 2)), ('blank', 2, 2),),
        ('grid_to_grid', 2, 1, 4, 4): (neg(('blank', 4, 3)), ('blank', 2, 2),),

        ('grid_to_grid', 2, 2, 1, 1): (('blank', 2, 3),),
        ('grid_to_grid', 2, 2, 1, 2): (neg(('blank', 1, 1)), ('blank', 2, 3),),
        ('grid_to_grid', 2, 2, 1, 3): (neg(('blank', 1, 2)), ('blank', 2, 3),),
        ('grid_to_grid', 2, 2, 1, 4): (neg(('blank', 1, 3)), ('blank', 2, 3),),
        ('grid_to_grid', 2, 2, 3, 1): (('blank', 2, 3),),
        ('grid_to_grid', 2, 2, 3, 2): (neg(('blank', 3, 1)), ('blank', 2, 3),),
        ('grid_to_grid', 2, 2, 3, 3): (neg(('blank', 3, 2)), ('blank', 2, 3),),
        ('grid_to_grid', 2, 2, 3, 4): (neg(('blank', 3, 3)), ('blank', 2, 3),),
        ('grid_to_grid', 2, 2, 4, 1): (('blank', 2, 3),),
        ('grid_to_grid', 2, 2, 4, 2): (neg(('blank', 4, 1)), ('blank', 2, 3),),
        ('grid_to_grid', 2, 2, 4, 3): (neg(('blank', 4, 2)), ('blank', 2, 3),),
        ('grid_to_grid', 2, 2, 4, 4): (neg(('blank', 4, 3)), ('blank', 2, 3),),

        ('grid_to_grid', 2, 3, 1, 1): (('blank', 2, 4),),
        ('grid_to_grid', 2, 3, 1, 2): (neg(('blank', 1, 1)), ('blank', 2, 4),),
        ('grid_to_grid', 2, 3, 1, 3): (neg(('blank', 1, 2)), ('blank', 2, 4),),
        ('grid_to_grid', 2, 3, 1, 4): (neg(('blank', 1, 3)), ('blank', 2, 4),),
        ('grid_to_grid', 2, 3, 3, 1): (('blank', 2, 4),),
        ('grid_to_grid', 2, 3, 3, 2): (neg(('blank', 3, 1)), ('blank', 2, 4),),
        ('grid_to_grid', 2, 3, 3, 3): (neg(('blank', 3, 2)), ('blank', 2, 4),),
        ('grid_to_grid', 2, 3, 3, 4): (neg(('blank', 3, 3)), ('blank', 2, 4),),
        ('grid_to_grid', 2, 3, 4, 1): (('blank', 2, 4),),
        ('grid_to_grid', 2, 3, 4, 2): (neg(('blank', 4, 1)), ('blank', 2, 4),),
        ('grid_to_grid', 2, 3, 4, 3): (neg(('blank', 4, 2)), ('blank', 2, 4),),
        ('grid_to_grid', 2, 3, 4, 4): (neg(('blank', 4, 3)), ('blank', 2, 4),),

        ('grid_to_grid', 2, 4, 1, 2): (neg(('blank', 1, 1)),),
        ('grid_to_grid', 2, 4, 1, 3): (neg(('blank', 1, 2)),),
        ('grid_to_grid', 2, 4, 1, 4): (neg(('blank', 1, 3)),),
        ('grid_to_grid', 2, 4, 3, 2): (neg(('blank', 3, 1)),),
        ('grid_to_grid', 2, 4, 3, 3): (neg(('blank', 3, 2)),),
        ('grid_to_grid', 2, 4, 3, 4): (neg(('blank', 3, 3)),),
        ('grid_to_grid', 2, 4, 4, 2): (neg(('blank', 4, 1)),),
        ('grid_to_grid', 2, 4, 4, 3): (neg(('blank', 4, 2)),),
        ('grid_to_grid', 2, 4, 4, 4): (neg(('blank', 4, 3)),),

        ('grid_to_grid', 3, 1, 2, 1): (('blank', 3, 2),),
        ('grid_to_grid', 3, 1, 2, 2): (neg(('blank', 2, 1)), ('blank', 3, 2),),
        ('grid_to_grid', 3, 1, 2, 3): (neg(('blank', 2, 2)), ('blank', 3, 2),),
        ('grid_to_grid', 3, 1, 2, 4): (neg(('blank', 2, 3)), ('blank', 3, 2),),
        ('grid_to_grid', 3, 1, 1, 1): (('blank', 3, 2),),
        ('grid_to_grid', 3, 1, 1, 2): (neg(('blank', 1, 1)), ('blank', 3, 2),),
        ('grid_to_grid', 3, 1, 1, 3): (neg(('blank', 1, 2)), ('blank', 3, 2),),
        ('grid_to_grid', 3, 1, 1, 4): (neg(('blank', 1, 3)), ('blank', 3, 2),),
        ('grid_to_grid', 3, 1, 4, 1): (('blank', 3, 2),),
        ('grid_to_grid', 3, 1, 4, 2): (neg(('blank', 4, 1)), ('blank', 3, 2),),
        ('grid_to_grid', 3, 1, 4, 3): (neg(('blank', 4, 2)), ('blank', 3, 2),),
        ('grid_to_grid', 3, 1, 4, 4): (neg(('blank', 4, 3)), ('blank', 3, 2),),

        ('grid_to_grid', 3, 2, 2, 1): (('blank', 3, 3),),
        ('grid_to_grid', 3, 2, 2, 2): (neg(('blank', 2, 1)), ('blank', 3, 3),),
        ('grid_to_grid', 3, 2, 2, 3): (neg(('blank', 2, 2)), ('blank', 3, 3),),
        ('grid_to_grid', 3, 2, 2, 4): (neg(('blank', 2, 3)), ('blank', 3, 3),),
        ('grid_to_grid', 3, 2, 1, 1): (('blank', 3, 3),),
        ('grid_to_grid', 3, 2, 1, 2): (neg(('blank', 1, 1)), ('blank', 3, 3),),
        ('grid_to_grid', 3, 2, 1, 3): (neg(('blank', 1, 2)), ('blank', 3, 3),),
        ('grid_to_grid', 3, 2, 1, 4): (neg(('blank', 1, 3)), ('blank', 3, 3),),
        ('grid_to_grid', 3, 2, 4, 1): (('blank', 3, 3),),
        ('grid_to_grid', 3, 2, 4, 2): (neg(('blank', 4, 1)), ('blank', 3, 3),),
        ('grid_to_grid', 3, 2, 4, 3): (neg(('blank', 4, 2)), ('blank', 3, 3),),
        ('grid_to_grid', 3, 2, 4, 4): (neg(('blank', 4, 3)), ('blank', 3, 3),),

        ('grid_to_grid', 3, 3, 2, 1): (('blank', 3, 4),),
        ('grid_to_grid', 3, 3, 2, 2): (neg(('blank', 2, 1)), ('blank', 3, 4),),
        ('grid_to_grid', 3, 3, 2, 3): (neg(('blank', 2, 2)), ('blank', 3, 4),),
        ('grid_to_grid', 3, 3, 2, 4): (neg(('blank', 2, 3)), ('blank', 3, 4),),
        ('grid_to_grid', 3, 3, 1, 1): (('blank', 3, 4),),
        ('grid_to_grid', 3, 3, 1, 2): (neg(('blank', 1, 1)), ('blank', 3, 4),),
        ('grid_to_grid', 3, 3, 1, 3): (neg(('blank', 1, 2)), ('blank', 3, 4),),
        ('grid_to_grid', 3, 3, 1, 4): (neg(('blank', 1, 3)), ('blank', 3, 4),),
        ('grid_to_grid', 3, 3, 4, 1): (('blank', 3, 4),),
        ('grid_to_grid', 3, 3, 4, 2): (neg(('blank', 4, 1)), ('blank', 3, 4),),
        ('grid_to_grid', 3, 3, 4, 3): (neg(('blank', 4, 2)), ('blank', 3, 4),),
        ('grid_to_grid', 3, 3, 4, 4): (neg(('blank', 4, 3)), ('blank', 3, 4),),

        ('grid_to_grid', 3, 4, 2, 2): (neg(('blank', 2, 1)),),
        ('grid_to_grid', 3, 4, 2, 3): (neg(('blank', 2, 2)),),
        ('grid_to_grid', 3, 4, 2, 4): (neg(('blank', 2, 3)),),
        ('grid_to_grid', 3, 4, 1, 2): (neg(('blank', 1, 1)),),
        ('grid_to_grid', 3, 4, 1, 3): (neg(('blank', 1, 2)),),
        ('grid_to_grid', 3, 4, 1, 4): (neg(('blank', 1, 3)),),
        ('grid_to_grid', 3, 4, 4, 2): (neg(('blank', 4, 1)),),
        ('grid_to_grid', 3, 4, 4, 3): (neg(('blank', 4, 2)),),
        ('grid_to_grid', 3, 4, 4, 4): (neg(('blank', 4, 3)),),

        ('grid_to_grid', 4, 1, 2, 1): (('blank', 4, 2),),
        ('grid_to_grid', 4, 1, 2, 2): (neg(('blank', 2, 1)), ('blank', 4, 2),),
        ('grid_to_grid', 4, 1, 2, 3): (neg(('blank', 2, 2)), ('blank', 4, 2),),
        ('grid_to_grid', 4, 1, 2, 4): (neg(('blank', 2, 3)), ('blank', 4, 2),),
        ('grid_to_grid', 4, 1, 3, 1): (('blank', 4, 2),),
        ('grid_to_grid', 4, 1, 3, 2): (neg(('blank', 3, 1)), ('blank', 4, 2),),
        ('grid_to_grid', 4, 1, 3, 3): (neg(('blank', 3, 2)), ('blank', 4, 2),),
        ('grid_to_grid', 4, 1, 3, 4): (neg(('blank', 3, 3)), ('blank', 4, 2),),
        ('grid_to_grid', 4, 1, 1, 1): (('blank', 4, 2),),
        ('grid_to_grid', 4, 1, 1, 2): (neg(('blank', 1, 1)), ('blank', 4, 2),),
        ('grid_to_grid', 4, 1, 1, 3): (neg(('blank', 1, 2)), ('blank', 4, 2),),
        ('grid_to_grid', 4, 1, 1, 4): (neg(('blank', 1, 3)), ('blank', 4, 2),),

        ('grid_to_grid', 4, 2, 2, 1): (('blank', 4, 3),),
        ('grid_to_grid', 4, 2, 2, 2): (neg(('blank', 2, 1)), ('blank', 4, 3),),
        ('grid_to_grid', 4, 2, 2, 3): (neg(('blank', 2, 2)), ('blank', 4, 3),),
        ('grid_to_grid', 4, 2, 2, 4): (neg(('blank', 2, 3)), ('blank', 4, 3),),
        ('grid_to_grid', 4, 2, 3, 1): (('blank', 4, 3),),
        ('grid_to_grid', 4, 2, 3, 2): (neg(('blank', 3, 1)), ('blank', 4, 3),),
        ('grid_to_grid', 4, 2, 3, 3): (neg(('blank', 3, 2)), ('blank', 4, 3),),
        ('grid_to_grid', 4, 2, 3, 4): (neg(('blank', 3, 3)), ('blank', 4, 3),),
        ('grid_to_grid', 4, 2, 1, 1): (('blank', 4, 3),),
        ('grid_to_grid', 4, 2, 1, 2): (neg(('blank', 1, 1)), ('blank', 4, 3),),
        ('grid_to_grid', 4, 2, 1, 3): (neg(('blank', 1, 2)), ('blank', 4, 3),),
        ('grid_to_grid', 4, 2, 1, 4): (neg(('blank', 1, 3)), ('blank', 4, 3),),

        ('grid_to_grid', 4, 3, 2, 1): (('blank', 4, 4),),
        ('grid_to_grid', 4, 3, 2, 2): (neg(('blank', 2, 1)), ('blank', 4, 4),),
        ('grid_to_grid', 4, 3, 2, 3): (neg(('blank', 2, 2)), ('blank', 4, 4),),
        ('grid_to_grid', 4, 3, 2, 4): (neg(('blank', 2, 3)), ('blank', 4, 4),),
        ('grid_to_grid', 4, 3, 3, 1): (('blank', 4, 4),),
        ('grid_to_grid', 4, 3, 3, 2): (neg(('blank', 3, 1)), ('blank', 4, 4),),
        ('grid_to_grid', 4, 3, 3, 3): (neg(('blank', 3, 2)), ('blank', 4, 4),),
        ('grid_to_grid', 4, 3, 3, 4): (neg(('blank', 3, 3)), ('blank', 4, 4),),
        ('grid_to_grid', 4, 3, 1, 1): (('blank', 4, 4),),
        ('grid_to_grid', 4, 3, 1, 2): (neg(('blank', 1, 1)), ('blank', 4, 4),),
        ('grid_to_grid', 4, 3, 1, 3): (neg(('blank', 1, 2)), ('blank', 4, 4),),
        ('grid_to_grid', 4, 3, 1, 4): (neg(('blank', 1, 3)), ('blank', 4, 4),),

        ('grid_to_grid', 4, 4, 2, 2): (neg(('blank', 2, 1)),),
        ('grid_to_grid', 4, 4, 2, 3): (neg(('blank', 2, 2)),),
        ('grid_to_grid', 4, 4, 2, 4): (neg(('blank', 2, 3)),),
        ('grid_to_grid', 4, 4, 3, 2): (neg(('blank', 3, 1)),),
        ('grid_to_grid', 4, 4, 3, 3): (neg(('blank', 3, 2)),),
        ('grid_to_grid', 4, 4, 3, 4): (neg(('blank', 3, 3)),),
        ('grid_to_grid', 4, 4, 1, 2): (neg(('blank', 1, 1)),),
        ('grid_to_grid', 4, 4, 1, 3): (neg(('blank', 1, 2)),),
        ('grid_to_grid', 4, 4, 1, 4): (neg(('blank', 1, 3)),),

    }

    return {} #precedence
